// ─────────────────────────────────────────────────────────────
//  dishAliases.js  —  Dish name → ingredient key expansion
//  All ingredient strings use underscore-keyed NUTRITION_DB keys.
//  Input normalized by normalizeInput.js before reaching this.
// ─────────────────────────────────────────────────────────────

export const DISH_ALIASES = {
  // ── Odia ────────────────────────────────────────────────────
  dalma:                ["toor_dal","pumpkin","raw_banana","papaya","turmeric","cumin","ghee"],

  // ── North Indian ────────────────────────────────────────────
  khichdi:              ["rice","moong_dal","turmeric","ghee","ginger"],
  paneer_butter_masala: ["paneer","tomato","cream","butter","cashews"],
  chole_bhature:        ["chickpeas","onion","tomato","ginger","garlic","flour"],
  aloo_paratha:         ["whole_wheat_flour","potato","coriander","ghee"],
  rajma_chawal:         ["rajma","rice","onion","tomato","ginger","cumin"],
  butter_chicken:       ["chicken","tomato","butter","cream","ginger","garlic"],
  pav_bhaji:            ["potato","green_peas","cauliflower","butter"],
  palak_paneer:         ["spinach","paneer","garlic","cream"],
  kadai_paneer:         ["paneer","capsicum","onion","tomato"],
  malai_kofta:          ["paneer","potato","cream","cashews","tomato"],
  bhindi_masala:        ["okra","onion","tomato","cumin"],
  dum_aloo:             ["potato","curd","ginger","mustard_oil"],
  vada_pav:             ["potato","gram_flour","garlic","mustard_seeds"],
  rasam:                ["tomato","black_pepper","cumin","garlic"],
  shahi_paneer:         ["paneer","cream","curd","cashews"],
  kheer:                ["rice","milk","sugar","cardamom","almonds"],
  aloo_gobi:            ["potato","cauliflower","onion","tomato","turmeric","cumin"],
  matar_paneer:         ["paneer","green_peas","tomato","onion","cream"],
  daal_makhani:         ["urad_dal","rajma","butter","cream","tomato","ginger","garlic"],
  gajar_halwa:          ["carrot","milk","sugar","ghee","khoya"],
  rogan_josh:           ["lamb","curd","ginger","garlic"],
  laal_maas:            ["lamb","garlic","ghee","curd"],
  nihari:               ["lamb","ginger","ghee"],
  haleem:               ["lamb","masoor_dal","ginger","garlic","onion","ghee"],
  shahi_tukda:          ["bread","milk","sugar","ghee","almonds"],
  keema_matar:          ["beef","green_peas","onion","tomato","ginger","garlic","cumin"],
  mutton_curry:         ["lamb","onion","tomato","garlic","ginger"],
  paneer_tikka:         ["paneer","curd","capsicum","onion","ginger","garlic"],
  chicken_tikka:        ["chicken","curd","ginger","garlic","lemon"],
  bedmi_puri:           ["whole_wheat_flour","urad_dal","cumin","ginger"],
  sabudana_khichdi:     ["sago","potato","peanuts","cumin","ghee"],
  shahi_korma:          ["lamb","cashews","cream","curd","saffron"],
  doi_maach:            ["fish","curd","turmeric","mustard_oil"],
  mutton_do_pyaza:      ["lamb","onion","ginger","garlic","curd"],

  // ── South Indian ────────────────────────────────────────────
  sambar:               ["toor_dal","tomato","onion","turmeric","drumstick"],
  idli:                 ["rice","urad_dal"],
  dosa:                 ["rice","urad_dal","chana_dal"],
  upma:                 ["semolina","urad_dal","onion","ginger"],
  pongal:               ["rice","moong_dal","black_pepper","cumin","ghee","cashews"],
  pesarattu:            ["moong_dal","ginger","onion"],
  uttapam:              ["rice","urad_dal","onion","tomato"],
  appam:                ["rice","coconut_milk","urad_dal"],
  avial:                ["raw_banana","carrot","pumpkin","curd","turmeric"],
  thoran:               ["cabbage","coconut","turmeric","mustard_seeds"],
  kootu:                ["chickpeas","pumpkin","coconut","cumin"],
  chettinad_chicken:    ["chicken","black_pepper","garlic","ginger","coconut"],
  fish_molee:           ["fish","coconut_milk","turmeric","ginger","onion"],
  kerala_prawn:         ["shrimp","coconut_milk","mustard_seeds"],
  fish_curry:           ["fish","turmeric","mustard_oil","onion","tomato"],
  baingan_bharta:       ["eggplant","onion","tomato","garlic"],
  dhokla:               ["gram_flour","lemon","curd"],
  lemon_rice:           ["rice","lemon","mustard_seeds","turmeric","peanuts"],
  masala_dosa:          ["rice","urad_dal","potato","onion","mustard_seeds","turmeric"],
  baingan_fry:          ["eggplant","turmeric","mustard_oil"],
  vermicelli_upma:      ["semolina","green_peas","carrot","mustard_seeds"],
  curd_rice:            ["rice","curd","mustard_seeds","ginger","carrot"],
  tamarind_rice:        ["rice","tamarind","peanuts","mustard_seeds","turmeric"],

  // ── Street Food & Breakfast ──────────────────────────────────
  poha:                 ["flattened_rice","peanuts","onion","turmeric"],
  besan_chilla:         ["gram_flour","onion","tomato","turmeric"],
  aloo_tikki:           ["potato","coriander"],
  kathi_roll:           ["whole_wheat_flour","chicken","onion","capsicum","egg"],

  // ── Biryani & Rice ───────────────────────────────────────────
  chicken_biryani:      ["rice","chicken","curd","onion","ghee","saffron"],
  mutton_biryani:       ["rice","lamb","curd","onion","ghee","ginger"],
  veg_biryani:          ["rice","carrot","green_peas","potato","curd"],
  egg_biryani:          ["rice","egg","onion","tomato","ghee","curd"],
  fried_rice:           ["rice","soy_sauce","carrot","green_peas","egg","garlic"],
  egg_fried_rice:       ["rice","egg","soy_sauce","garlic","green_peas"],
  congee:               ["rice","ginger","soy_sauce"],

  // ── Chicken ──────────────────────────────────────────────────
  chicken_curry:        ["chicken","onion","tomato","ginger","garlic","turmeric"],
  chicken_65:           ["chicken","curd","garlic","ginger"],
  chicken_stew:         ["chicken","coconut_milk","potato","carrot","ginger"],
  honey_garlic_chicken: ["chicken","honey","garlic","soy_sauce","sesame_oil"],
  chicken_shawarma:     ["chicken","curd","garlic","lemon","tahini"],

  // ── Global Favourites ────────────────────────────────────────
  miso_soup:            ["tofu","mushroom","seaweed","miso_paste"],
  pasta_carbonara:      ["pasta","egg","parmesan","black_pepper"],
  guacamole:            ["avocado","onion","tomato","lemon","coriander"],
  thai_green_curry:     ["coconut_milk","chicken","capsicum","lemongrass"],
  hummus:               ["chickpeas","tahini","olive_oil","lemon","garlic"],
  falafel:              ["chickpeas","garlic","cumin","coriander","flour"],
  pizza_margherita:     ["flour","tomato","mozzarella","olive_oil","basil"],
  tacos:                ["corn_tortillas","beef","lettuce","tomato","onion"],
  hakka_noodles:        ["noodles","cabbage","carrot","capsicum","soy_sauce"],
  ramen:                ["egg","mushroom","soy_sauce","ramen_noodles"],
  spaghetti_bolognese:  ["pasta","beef","tomato","onion","garlic","oregano"],
  oatmeal:              ["oats","milk","honey","banana","almonds"],
  bibimbap:             ["rice","egg","spinach","carrot","mushroom","soy_sauce"],
  pad_thai:             ["rice_noodles","shrimp","egg","peanuts"],
  pho:                  ["rice_noodles","beef","broth","ginger","onion"],
  shawarma:             ["chicken","curd","garlic","lemon","pita_bread"],
  fajitas:              ["chicken","capsicum","onion","lime"],
  greek_salad:          ["cucumber","tomato","feta_cheese","olives","onion","olive_oil"],
  laksa:                ["rice_noodles","coconut_milk","shrimp","tofu"],
  shakshuka:            ["egg","tomato","capsicum","onion","olive_oil"],
  ratatouille:          ["eggplant","zucchini","tomato","capsicum","onion","olive_oil"],
  lasagna:              ["pasta","beef","tomato","mozzarella","parmesan","ricotta_cheese"],
  pancakes:             ["flour","milk","egg","butter","sugar"],
  waffles:              ["flour","milk","egg","butter","sugar","blueberries"],
  french_toast:         ["bread","egg","milk","sugar","butter"],
  smoothie_bowl:        ["banana","blueberries","curd","honey","almonds"],
  mushrooms_risotto:    ["rice","mushroom","onion","garlic","butter","parmesan"],
  shepherds_pie:        ["beef","potato","green_peas","carrot","onion","butter"],
  sushi_rolls:          ["rice","fish","cucumber","avocado","seaweed"],
  tom_yum_soup:         ["shrimp","mushroom","lemon","lemongrass","fish_sauce"],
  fish_and_chips:       ["fish","potato","flour","lemon"],
  quinoa_salad:         ["quinoa","cucumber","tomato","lemon","olive_oil","parsley"],
  roast_turkey:         ["turkey","butter","garlic","rosemary","onion"],
  beef_burger:          ["beef","buns","lettuce","tomato","onion","mayonnaise"],
  veggie_burger:        ["soy_chunks","buns","lettuce","tomato","onion"],
  egg_salad:            ["egg","mayonnaise","onion","black_pepper"],
  pork_vindaloo:        ["pork","garlic","ginger","cumin","vinegar"],
  caesar_salad:         ["lettuce","chicken","parmesan","mayonnaise","garlic","croutons"],
  avocado_toast:        ["bread","avocado","lemon","black_pepper"],
  shrimp_scampi:        ["shrimp","pasta","butter","garlic","lemon"],
  beef_stir_fry:        ["beef","broccoli","capsicum","soy_sauce","ginger","garlic"],
  lentil_soup:          ["masoor_dal","carrot","onion","garlic","cumin","turmeric"],
  chicken_tikka:        ["chicken","curd","ginger","garlic","lemon"],
  okonomiyaki:          ["cabbage","egg","flour","soy_sauce"],
}
